### ISSUE TITLE
用 Go 自带的 form 生成可能不能满足部分要求

### ISSUE THREAD

**Issue by aimerforreimu** [guonaihong/gout#125]
https://github.com/guonaihong/gout/blob/7f7d32a6cc3f1b286658a31f86d9427d46a0cff6/encode/form.go#L52

中生成表单字段的部分使用了 `f.CreateFormFile`

```golang
part, err := f.CreateFormFile(key, filepath.Base(key),"image/png")
	if err != nil {
		return err
	}
```

正常这个函数生成的 form 的 `Content-Type` 和 `Content-Disposition` 是默认的

```golang
func (w *Writer) CreateFormFile(fieldname, filename string) (io.Writer, error) {
	h := make(textproto.MIMEHeader)
	h.Set("Content-Disposition",
		fmt.Sprintf(`form-data; name="%s"; filename="%s"`,
			escapeQuotes(fieldname), escapeQuotes(filename)))
	h.Set("Content-Type", "application/octet-stream")
	return w.CreatePart(h)
}
```

是否考虑重写这个函数做到可以自定义 filename 和 Content-Type

**Comment by guonaihong** [comment]
这个修改是好修改，官方代码这么encode数据，有没有rfc规定？
我先看下http server解析相关文档，如果送给http server和nginx没问题就可以加修改Content-Type的配置。

**Comment by aimerforreimu** [comment]
嗯嗯，感谢，另外我记得看到过您发了一个总体设计的图片，不知道为什么找不到了，能给一下地址吗，我想学习一下您的代码

**Comment by guonaihong** [comment]
图片在https://github.com/guonaihong/images 这个仓库里面。
倒数第二个commit就可以找到。(最新commit删除掉了)
目录在images/gout/gout.png

**Comment by guonaihong** [comment]
这个功能下周可以开始。如果急的要的话可以和我说下。。。

**Comment by aimerforreimu** [comment]
不急，如果有什么功能也可以说一下，我看看我能不能帮忙写一点

**Comment by guonaihong** [comment]
欢迎欢迎，那可以先试下这个功能的开发？然后我帮你把把关。如果有不了解的地方，可以问我。

**Comment by aimerforreimu** [comment]
ok,这个功能先交给我吧

**Comment by aimerforreimu** [comment]
您好，我阅读了您的代码下面有几点疑问和一些我对这个功能的实现想法：

**疑问**：
我看到您在文档中说  `core.FormFile` 与 `core.FormMem` 这两个类型分别表示从内存中读取和从文件地址中读取，既然已经确定是要写入的是表单文件 (FormFile) ，是否应该使用 F**ro**m 而不是 F**or**m  去表示「从....中读取」的意思。

**实现这个功能的想法:**
我想在 `core/core.go` 中定义一个新的 `struct`

```golang
//Content-Disposition:[form-data; name="file"; filename="file"]
//Content-Type:[application/octet-stream]
type FormFile struct {
	Field       string      //name
	FileName    string      //filename
	ContentType string      //Content-Type:Mime-Type
	File        interface{}  //FromFile | FromMem (这里就是您的从文件地址中读取和从内存中读取)
}
```

然后在 `encode/form.go` 中的 `Add` 方法进行对应的解析修改。

您感觉可以吗？

**Comment by guonaihong** [comment]
我等会儿要去火车站。回去之后可以仔细看下。------------------ 原始邮件 ------------------
发件人: "aimerforreimu"<notifications@github.com>
发送时间: 2019年12月13日(星期五) 下午5:43
收件人: "guonaihong/gout"<gout@noreply.github.com>;
抄送: "guonaihong"<guonaihong@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [guonaihong/gout] 用 Go 自带的 form 生成可能不能满足部分要求 (#125)



您好，我阅读了您的代码下面有几点疑问和一些我对这个功能的实现想法：
 
疑问：
 我看到您在文档中说  core.FormFile 与 core.FormMem 这两个类型分别表示从内存中读取和从文&#x4EF6;地址中读取，既然已经确定是要写入的是表单文&#x4EF6; (FormFile) ，是否应该使用 From 而不是 Form  去表示「从....中读取」的意思。
 
实现这个功能的想法:
 我想在 core/core.go 中定义一个新的 struct
 //Content-Disposition:[form-data; name="file"; filename="file"] //Content-Type:[application/octet-stream] type FormFile struct { 	Field       string      //name 	FileName    string      //filename 	ContentType string      //Content-Type:Mime-Type 	File        interface{}  //FromFile | FromMem (这里就是您的从文&#x4EF6;地址中读取和从内存中读取) }
 
然后在 encode/form.go 中的 Add 方法进行对应的解析修改。
 
您感觉可以吗？
 
&mdash;

**Comment by guonaihong** [comment]
设计看过了，可行。
可以给core.FormMem和&nbsp;core.FormFile type两个别名core.FromMem和&nbsp;core.FromFile

**Comment by guonaihong** [comment]
@aimerforreimu 在readme.md里面和example加下例子。

**Comment by aimerforreimu** [comment]
好的，顺便我今天开搞翻译

**Comment by guonaihong** [comment]
@aimerforreimu 最近可有时间完善下readme.md。如果没有的话，我这边加下。下周一打算发布v0.0.5版本。

**Comment by aimerforreimu** [comment]
周日周六要考研，周一有空了

guonaihong <notifications@github.com>于2019年12月20日 周五下午12:46写道：

**Comment by guonaihong** [comment]
@aimerforreimu ok

**Comment by guonaihong** [comment]
这个issue先关了。
