### ISSUE TITLE
please consider replacing the `net/http` package with `github.com/valyala/fasthttp`

### ISSUE THREAD

**Issue by jan4984** [guonaihong/gout#218]
according to the performance burst.
https://github.com/valyala/fasthttp#http-client-comparison-with-nethttp

**Comment by guonaihong** [comment]
ok

**Comment by guonaihong** [comment]
fasthttp为了减少调用malloc函数，对API做了很多假设，把gout适配到fasthttp改动太大，时间延期下。

**Comment by jan4984** [comment]
fasthttp挺垃圾的
