### ISSUE TITLE
../../guonaihong/gout/decode/yaml.go:23:12: undefined: yaml.NewDecoder

### ISSUE THREAD

**Issue by botsphp** [guonaihong/gout#220]
go version go1.14.1 darwin/amd64

`go get` 出现

```
# github.com/guonaihong/gout/decode
../../guonaihong/gout/decode/yaml.go:23:12: undefined: yaml.NewDecoder
../../guonaihong/gout/decode/yaml.go:29:12: undefined: yaml.NewDecoder
# github.com/guonaihong/gout/encode
../../guonaihong/gout/encode/yaml.go:35:12: undefined: yaml.NewEncoder
```

`go mod graph` 结果
```
github.com/guonaihong/gout github.com/gin-gonic/gin@v1.5.0
github.com/guonaihong/gout github.com/google/uuid@v1.1.1
github.com/guonaihong/gout github.com/mattn/go-isatty@v0.0.9
github.com/guonaihong/gout github.com/stretchr/testify@v1.4.0
github.com/guonaihong/gout golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa
github.com/guonaihong/gout gopkg.in/yaml.v2@v2.2.2
golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2
golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a
golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa golang.org/x/text@v0.3.0
github.com/mattn/go-isatty@v0.0.9 golang.org/x/sys@v0.0.0-20190813064441-fde4db37ae7a
github.com/stretchr/testify@v1.4.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.4.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.4.0 github.com/stretchr/objx@v0.1.0
github.com/stretchr/testify@v1.4.0 gopkg.in/yaml.v2@v2.2.2
github.com/gin-gonic/gin@v1.5.0 github.com/gin-contrib/sse@v0.1.0
github.com/gin-gonic/gin@v1.5.0 github.com/go-playground/locales@v0.12.1
github.com/gin-gonic/gin@v1.5.0 github.com/go-playground/universal-translator@v0.16.0
github.com/gin-gonic/gin@v1.5.0 github.com/golang/protobuf@v1.3.2
github.com/gin-gonic/gin@v1.5.0 github.com/json-iterator/go@v1.1.7
github.com/gin-gonic/gin@v1.5.0 github.com/leodido/go-urn@v1.1.0
github.com/gin-gonic/gin@v1.5.0 github.com/mattn/go-isatty@v0.0.9
github.com/gin-gonic/gin@v1.5.0 github.com/stretchr/testify@v1.4.0
github.com/gin-gonic/gin@v1.5.0 github.com/ugorji/go/codec@v1.1.7
github.com/gin-gonic/gin@v1.5.0 gopkg.in/go-playground/assert.v1@v1.2.1
github.com/gin-gonic/gin@v1.5.0 gopkg.in/go-playground/validator.v9@v9.29.1
github.com/gin-gonic/gin@v1.5.0 gopkg.in/yaml.v2@v2.2.2
github.com/json-iterator/go@v1.1.7 github.com/davecgh/go-spew@v1.1.1
github.com/json-iterator/go@v1.1.7 github.com/google/gofuzz@v1.0.0
github.com/json-iterator/go@v1.1.7 github.com/modern-go/concurrent@v0.0.0-20180228061459-e0a39a4cb421
github.com/json-iterator/go@v1.1.7 github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742
github.com/json-iterator/go@v1.1.7 github.com/stretchr/testify@v1.3.0
golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2 golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a
gopkg.in/yaml.v2@v2.2.2 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
github.com/gin-contrib/sse@v0.1.0 github.com/stretchr/testify@v1.3.0
github.com/stretchr/testify@v1.3.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.3.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.3.0 github.com/stretchr/objx@v0.1.0
github.com/ugorji/go/codec@v1.1.7 github.com/ugorji/go@v1.1.7
github.com/ugorji/go@v1.1.7 github.com/ugorji/go/codec@v1.1.7
```

**Comment by guonaihong** [comment]
我看下。

**Comment by guonaihong** [comment]
直接cd _example目录，然后go run 01-color-json.go，结果是？

**Comment by guonaihong** [comment]
hi @botsphp 我的输出如下，这边的gout是有版本号的。
main github.com/gin-gonic/gin@v1.6.3
main github.com/guonaihong/gout@v0.0.11
github.com/guonaihong/gout@v0.0.11 github.com/gin-gonic/gin@v1.5.0
github.com/guonaihong/gout@v0.0.11 github.com/google/uuid@v1.1.1
github.com/guonaihong/gout@v0.0.11 github.com/mattn/go-isatty@v0.0.9
github.com/guonaihong/gout@v0.0.11 github.com/stretchr/testify@v1.4.0
github.com/guonaihong/gout@v0.0.11 golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa
github.com/guonaihong/gout@v0.0.11 gopkg.in/yaml.v2@v2.2.2
github.com/gin-gonic/gin@v1.5.0 github.com/gin-contrib/sse@v0.1.0
github.com/gin-gonic/gin@v1.5.0 github.com/go-playground/locales@v0.12.1
github.com/gin-gonic/gin@v1.5.0 github.com/go-playground/universal-translator@v0.16.0
github.com/gin-gonic/gin@v1.5.0 github.com/golang/protobuf@v1.3.2
github.com/gin-gonic/gin@v1.5.0 github.com/json-iterator/go@v1.1.7
github.com/gin-gonic/gin@v1.5.0 github.com/leodido/go-urn@v1.1.0
github.com/gin-gonic/gin@v1.5.0 github.com/mattn/go-isatty@v0.0.9
github.com/gin-gonic/gin@v1.5.0 github.com/stretchr/testify@v1.4.0
github.com/gin-gonic/gin@v1.5.0 github.com/ugorji/go/codec@v1.1.7
github.com/gin-gonic/gin@v1.5.0 gopkg.in/go-playground/assert.v1@v1.2.1
github.com/gin-gonic/gin@v1.5.0 gopkg.in/go-playground/validator.v9@v9.29.1
github.com/gin-gonic/gin@v1.5.0 gopkg.in/yaml.v2@v2.2.2
github.com/stretchr/testify@v1.4.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.4.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.4.0 github.com/stretchr/objx@v0.1.0
github.com/stretchr/testify@v1.4.0 gopkg.in/yaml.v2@v2.2.2
github.com/json-iterator/go@v1.1.7 github.com/davecgh/go-spew@v1.1.1
github.com/json-iterator/go@v1.1.7 github.com/google/gofuzz@v1.0.0
github.com/json-iterator/go@v1.1.7 github.com/modern-go/concurrent@v0.0.0-20180228061459-e0a39a4cb421
github.com/json-iterator/go@v1.1.7 github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742
github.com/json-iterator/go@v1.1.7 github.com/stretchr/testify@v1.3.0
github.com/stretchr/testify@v1.3.0 github.com/davecgh/go-spew@v1.1.0
github.com/stretchr/testify@v1.3.0 github.com/pmezard/go-difflib@v1.0.0
github.com/stretchr/testify@v1.3.0 github.com/stretchr/objx@v0.1.0
golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2
golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a
golang.org/x/net@v0.0.0-20200114155413-6afb5195e5aa golang.org/x/text@v0.3.0
github.com/gin-contrib/sse@v0.1.0 github.com/stretchr/testify@v1.3.0
github.com/ugorji/go/codec@v1.1.7 github.com/ugorji/go@v1.1.7
golang.org/x/crypto@v0.0.0-20190308221718-c2843e01d9a2 golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a
gopkg.in/yaml.v2@v2.2.2 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405
github.com/ugorji/go@v1.1.7 github.com/ugorji/go/codec@v1.1.7
github.com/mattn/go-isatty@v0.0.9 golang.org/x/sys@v0.0.0-20190813064441-fde4db37ae7a
github.com/gin-gonic/gin@v1.6.3 github.com/gin-contrib/sse@v0.1.0
github.com/gin-gonic/gin@v1.6.3 github.com/go-playground/validator/v10@v10.2.0
github.com/gin-gonic/gin@v1.6.3 github.com/golang/protobuf@v1.3.3
github.com/gin-gonic/gin@v1.6.3 github.com/json-iterator/go@v1.1.9
github.com/gin-gonic/gin@v1.6.3 github.com/mattn/go-isatty@v0.0.12
github.com/gin-gonic/gin@v1.6.3 github.com/stretchr/testify@v1.4.0
github.com/gin-gonic/gin@v1.6.3 github.com/ugorji/go/codec@v1.1.7
github.com/gin-gonic/gin@v1.6.3 gopkg.in/yaml.v2@v2.2.8
github.com/json-iterator/go@v1.1.9 github.com/davecgh/go-spew@v1.1.1
github.com/json-iterator/go@v1.1.9 github.com/google/gofuzz@v1.0.0
github.com/json-iterator/go@v1.1.9 github.com/modern-go/concurrent@v0.0.0-20180228061459-e0a39a4cb421
github.com/json-iterator/go@v1.1.9 github.com/modern-go/reflect2@v0.0.0-20180701023420-4b7aa43c6742
github.com/json-iterator/go@v1.1.9 github.com/stretchr/testify@v1.3.0
github.com/mattn/go-isatty@v0.0.12 golang.org/x/sys@v0.0.0-20200116001909-b77594299b42
github.com/go-playground/validator/v10@v10.2.0 github.com/go-playground/assert/v2@v2.0.1
github.com/go-playground/validator/v10@v10.2.0 github.com/go-playground/locales@v0.13.0
github.com/go-playground/validator/v10@v10.2.0 github.com/go-playground/universal-translator@v0.17.0
github.com/go-playground/validator/v10@v10.2.0 github.com/leodido/go-urn@v1.2.0
github.com/go-playground/universal-translator@v0.17.0 github.com/go-playground/locales@v0.13.0
github.com/leodido/go-urn@v1.2.0 github.com/stretchr/testify@v1.4.0
github.com/go-playground/locales@v0.13.0 golang.org/x/text@v0.3.2
golang.org/x/text@v0.3.2 golang.org/x/tools@v0.0.0-20180917221912-90fa682c2a6e
gopkg.in/yaml.v2@v2.2.8 gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405

**Comment by guonaihong** [comment]
或者把你的go.mod贴出啦看下呢。。。

**Comment by botsphp** [comment]
多谢，我忘记回复了。

我是把整个 go mod 整个全删除重新拉就好了。

**Comment by guonaihong** [comment]
不客气。。。
