### ISSUE TITLE
设置Header 的时候报错，unknown type 

### ISSUE THREAD

**Issue by windghoul** [guonaihong/gout#230]
![image](https://user-images.githubusercontent.com/16053291/84745189-cc1ccd80-afe6-11ea-821e-39f62f27698a.png)
这个Header 应该是string string 类型，但是解析错误
![image](https://user-images.githubusercontent.com/16053291/84745223-ddfe7080-afe6-11ea-84cb-1fdc1cb5366f.png)

**Comment by guonaihong** [comment]
抱歉，图片看不了。可以贴下代码吗？

**Comment by guonaihong** [comment]
图片刷新出来了，我这边测试是可以的。
代码如下
```
package main

import (
	"fmt"

	"github.com/guonaihong/gout"
)

func main() {
	s := ""
	err := gout.GET(":4444").SetHeader(gout.H{"cookie": "hello"}).BindBody(&s).Do()
	fmt.Println(err)
}

```

**Comment by windghoul** [comment]
module curltool

go 1.14

require (
	github.com/guonaihong/gout v0.0.12
	github.com/sirupsen/logrus v1.6.0
)
那也有可能是我的服务有问题，您这边可以出一个报错信息自查表，这样可以方便知道哪里有问题了

**Comment by guonaihong** [comment]
好，这个建议我考虑下怎么实施。

**Comment by windghoul** [comment]
问题是出现在bindbody，我使用了一个struct 作为bindbody的入参，导致解析出错，问题已经解决，问题关闭
