### ISSUE TITLE
设置代理怎么加账号密码

### ISSUE THREAD

**Issue by stuhk** [guonaihong/gout#238]
如题

**Comment by guonaihong** [comment]
不挂代理，你的密码是放在下面的哪个方式？
1. http header的Authorization 字段里面？
1. url里面(http://username:password@hostname/)  ？

**Comment by stuhk** [comment]
http://username:password@hostname/   s5代理

**Comment by stuhk** [comment]
socks5

**Comment by guonaihong** [comment]
我刚刚，测试了下。url里面的username:password，会自动编码到Authorization 这个http header里面，按道理什么都不要修改。

**Comment by hughshen1996** [comment]
我设置完代理SetProxy，修改了DefaultClient，有什么重置DefaultClient的方法吗？
我第一次请求用代理，第二次请求不用代理，有删除代理的方法吗？
目前我是通过传自定义httpclient的方法。还有，有考虑在DefaultClient里面加上cookiejar来管理cookie吗？
	CurCookieJar, _ := cookiejar.New(nil)
	c := &http.Client{
		Jar: CurCookieJar,
	}

**Comment by guonaihong** [comment]
@hughshen1996  对于恢复DefaultClient
有两种做法
*使用一个单独的全局http.Client，专门用于Proxy使用，非proxy请求不使用这个http.Client
*断言```DefaultClient.Transport```接口为```*http.Transport```类型，然后设置为空```transport.Proxy = nil```。
* 或者有别的建议也欢迎讨论。
