### ISSUE TITLE
是不是像BindJSON这类的函数，如果返回的状态码是比如502之类的话，不应该解析的，解析肯定是出错的

### ISSUE THREAD

**Issue by chanyipiaomiao** [guonaihong/gout#243]
是不是像BindJSON这类的函数，如果返回的状态码是比如502之类的话，不应该解析的，解析肯定是出错的

**Comment by guonaihong** [comment]
BindJSON是否报错，依赖服务端返回接口数据格式。比如服务502返回的是json，那BindJSON不会报错。反之就会报错。

**Comment by chanyipiaomiao** [comment]
是这样，接口是nginx+服务端，是NGINX报的502，这时候BindJSON就出错了，BindJSON的时候能否判断一下状态码

**Comment by guonaihong** [comment]
可以使用Callback接口，文档有例子。现在不在电脑旁边，不然可以贴下代码。



---原始邮件---
发件人: "chanyipiaomiao"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 中午11:54
收件人: "guonaihong/gout"<gout@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"guonaihong"<guonaihong@qq.com&gt;;
主题: Re: [guonaihong/gout] 是不是像BindJSON这类的函数，如果返回的状态码是比如502之类的话，不应该解析的，解析肯定是出错的 (#243)




 
是这样，接口是nginx+服务端，是NGINX报的502，这时候BindJSON就出错了，BindJSON的时候能否判断一下状态码

**Comment by chanyipiaomiao** [comment]
OK 看到了。
