### ISSUE TITLE
发生302跳转的时候,没有带上cookie

### ISSUE THREAD

**Issue by ioxuy** [guonaihong/gout#254]
使用gout模拟登录:
	url := url.URL{Scheme: SCHEME, Host: HOST, Path: LOGIN_PATH}
	var res []byte
	code := 0
	g := gout.New(nil)
	err := g.POST(url.String()).
		SetWWWForm(core.H{
		"username": username,
		"password": password}).
		SetProxy("http://127.0.0.1:7001").
		Debug(true).
		BindBody(&res).
		Code(&code).
		Do()

	if err != nil || code != 200 {
		fmt.Printf("%s:code = %d\n", err, code)
		return g, err
	}

主要代码如上,不知哪里有误

**Comment by guonaihong** [comment]
是https还是http?

**Comment by ioxuy** [comment]
> 是https还是http?

http
![image](https://user-images.githubusercontent.com/7322644/90105582-b7577e80-dd78-11ea-84c6-f9aa67490db5.png)

**Comment by ioxuy** [comment]
> 是https还是http?

这是用其它包,模拟登录,只有两个请求
![image](https://user-images.githubusercontent.com/7322644/90105915-406eb580-dd79-11ea-9db9-6c68883bb220.png)

**Comment by guonaihong** [comment]
了解，我看下。

**Comment by guonaihong** [comment]
gout有3个请求，其实和RFC 7231有关系，标准库在处理301时，如果Method不是GET和HEAD，会修改成GET发送。
我确认下，服务端要的cookies，就是请求 http header里面有 Set-Cookie这个字段，并且有值对吧？

**Comment by ioxuy** [comment]
> gout有3个请求，其实和RFC 7231有关系，标准库在处理301时，如果Method不是GET和HEAD，会修改成GET发送。
> 我确认下，服务端要的cookies，就是请求 http header里面有 Set-Cookie这个字段，并且有值对吧？

是的
![image](https://user-images.githubusercontent.com/7322644/90108605-2636d680-dd7d-11ea-9f74-afe03ba6abb4.png)

**Comment by ioxuy** [comment]
这是抓包chls文件,不知用不用得上
[归档.zip](https://github.com/guonaihong/gout/files/5067864/default.zip)

**Comment by guonaihong** [comment]
现在流程是服务端生成cookie，然后客户端没有自动保存并且发送过来？可否把resty代码贴下。刚刚用net/http代码试下，服务如果有301跳转 client也不会发送cookie的，奇怪了。

**Comment by guonaihong** [comment]
不用了，是我服务端demo的原因。

**Comment by guonaihong** [comment]
客户端设置代码如下:
```go
 jar, err := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
        if err != nil {
                log.Fatal(err)
        }

        client := &http.Client{
                Jar: jar,
        }

        gout.New(client).GET(ts.URL).SetBody("hi cookie").Do()
        gout.New(client).GET(ts.URL).SetBody("hi cookie2").Do()

```

## 完整客户端服务端代码如下
```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"net/http/cookiejar"
	"net/http/httptest"

	"github.com/gin-gonic/gin"
	"github.com/guonaihong/gout"
	"golang.org/x/net/publicsuffix"
)

func server() *gin.Engine {
	r := gin.Default()
	r.GET("/", func(c *gin.Context) {

		cookie, err := c.Cookie("gin_cookie")

		if err != nil {
			cookie = "NotSet"
			c.SetCookie("gin_cookie", "test", 3600, "/", "", false, true)
		}

		fmt.Printf("Cookie value: %s \n", cookie)

	})

	return r
}

func main() {

	//ts := httptest.NewServer(http.HandlerFunc(router1))
	router2 := server()
	ts := httptest.NewServer(http.HandlerFunc(router2.ServeHTTP))
	defer ts.Close()

	// All users of cookiejar should import "golang.org/x/net/publicsuffix"
	jar, err := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
	if err != nil {
		log.Fatal(err)
	}

	client := &http.Client{
		Jar: jar,
	}

	gout.New(client).GET(ts.URL).SetBody("hi cookie").Do()
	gout.New(client).GET(ts.URL).SetBody("hi cookie2").Do()
}

```

**Comment by ioxuy** [comment]
> ## 客户端设置代码如下，自动持有服务端设置的cookie(对于提问，可用下面的代码解决)
> ```go
>         jar, err := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
>         if err != nil {
>                 log.Fatal(err)
>         }
> 
>         client := &http.Client{
>                 Jar: jar,
>         }
> 
>         gout.New(client).GET(ts.URL).SetBody("hi cookie").Do()
>         gout.New(client).GET(ts.URL).SetBody("hi cookie2").Do() //抓下包就可以看到自动持有服务端一开始设置的cookie了。
> ```
> 
> ## 完整客户端+服务端代码如下
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 	"net/http"
> 	"net/http/cookiejar"
> 	"net/http/httptest"
> 
> 	"github.com/gin-gonic/gin"
> 	"github.com/guonaihong/gout"
> 	"golang.org/x/net/publicsuffix"
> )
> 
> func server() *gin.Engine {
> 	r := gin.Default()
> 	r.GET("/", func(c *gin.Context) {
> 
> 		cookie, err := c.Cookie("gin_cookie")
> 
> 		if err != nil {
> 			cookie = "NotSet"
> 			c.SetCookie("gin_cookie", "test", 3600, "/", "", false, true)
> 		}
> 
> 		fmt.Printf("Cookie value: %s \n", cookie)
> 
> 	})
> 
> 	return r
> }
> 
> func main() {
> 
> 	//ts := httptest.NewServer(http.HandlerFunc(router1))
> 	router2 := server()
> 	ts := httptest.NewServer(http.HandlerFunc(router2.ServeHTTP))
> 	defer ts.Close()
> 
> 	// All users of cookiejar should import "golang.org/x/net/publicsuffix"
> 	jar, err := cookiejar.New(&cookiejar.Options{PublicSuffixList: publicsuffix.List})
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
> 	client := &http.Client{
> 		Jar: jar,
> 	}
> 
> 	gout.New(client).GET(ts.URL).SetBody("hi cookie").Do()
> 	gout.New(client).GET(ts.URL).SetBody("hi cookie2").Do()
> }
> ```

因为在外面办事,现在才看到,谢谢

**Comment by guonaihong** [comment]
ok
