### ISSUE TITLE
非benchmark模式可以设置concurrent吗

### ISSUE THREAD

**Issue by solarhell** [guonaihong/gout#256]
如题，用于爬虫，使用某些代理ip时，最大允许同时5次请求。目前暂时没有api来设置同时最大允许的并发数？

**Comment by guonaihong** [comment]
基于一些设计上的考虑，gout非benchmark，没有加并发限制。
你可以用```golang.org/x/sync/semaphore``` 这个库实现次数的限制，如果还想进一步对频率有限制，可以漏桶算法或者令牌环库，```https://github.com/golang/time```
