### ISSUE TITLE
Retry.getSleep 存在可能的 overflow 问题

### ISSUE THREAD

**Issue by Mrs4s** [guonaihong/gout#258]
https://github.com/guonaihong/gout/blob/5d2c07e290f5ca4c4f8d334743fcdb17a0c568b5/filter/retry.go#L92-L100
当 `GOARCH=386` 时, `int` 类型为 4 字节, 此时如果设置 `MaxWaitTime > time.Second * 4` 的话会造成
https://github.com/guonaihong/gout/blob/5d2c07e290f5ca4c4f8d334743fcdb17a0c568b5/filter/retry.go#L97
`temp` 大于 `int32` 的最大值, 在转换后出现负数 直到 `rand.Intn(int(temp))` 出现panic.

建议修改 `rand.Intn` 到 `rand.Int63n`

相关问题 : Mrs4s/go-cqhttp#373

**Comment by guonaihong** [comment]
ok。我加些32位平台的测试用例。

**Comment by guonaihong** [comment]
在v0.1.3版本已经修复。
