### ISSUE TITLE
使用SetJSON 方法的转义问题

### ISSUE THREAD

**Issue by gofromzero** [guonaihong/gout#262]
![image](https://user-images.githubusercontent.com/30290644/100564279-8edd9b00-32fb-11eb-9010-e90db1fe0730.png)
![image](https://user-images.githubusercontent.com/30290644/100564290-94d37c00-32fb-11eb-963f-bddbba64bd58.png)
使用SetJSON 之后 请求时 会将参数自动转义，这种转义是否能取消? 该如何设置？

**Comment by guonaihong** [comment]
我这边图片现在没刷出来，方便的话，可以贴下代码，和你想要的输出。

**Comment by guonaihong** [comment]
现在刷出来了，这个转义是json规范里面定义的。你反序列化，拿到的还是&符号，不影响业务的。

**Comment by gofromzero** [comment]
哦哦 了解了。
