### ISSUE TITLE
protobuf协议怎么用呢？

### ISSUE THREAD

**Issue by ayamzh** [guonaihong/gout#263]
protobuf协议怎么用呢？

**Comment by guonaihong** [comment]
http body里面放protobuf的数据包？

**Comment by guonaihong** [comment]
如果是的话，使用proto.Marhsal()出data。然后使用SetBody接口填充数据，就可以。

**Comment by guonaihong** [comment]
下个版本提供SetProtobuf接口，这样子用起来会更简单。

**Comment by ayamzh** [comment]
都行。。听老大的

**Comment by guonaihong** [comment]
v0.1.9已经包含SetProtoBuf接口，这个issue先关闭。有问题可打开。
