### ISSUE TITLE
如何支持 data-raw

### ISSUE THREAD

**Issue by botsphp** [guonaihong/gout#264]
```shell
curl 'https://google.com' \
-H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
--data-raw 'elapsed_time=0&user_choice_index=-1&ts=1608191572029' \
--compressed%
```

这样的请求怎么用 Gout 实现呢

**Comment by guonaihong** [comment]
```go
func main() {
    err := gout.POST("127.0.0.1:1234").SetWWWForm(
        gout.A{
            "elapsed_time", 0,
            "user_choice_index", -1, 
            "ts", 1608191572029,
        },
    ).Do()
    fmt.Println(err)
}

```

**Comment by guonaihong** [comment]
x-www-form-urlencoded 可以使用SetWWWForm接口构造数据。

**Comment by botsphp** [comment]
`charset=UTF-8`
现在有些 WebServer 需要添加这个参数，可能问题点在这里。

**Comment by guonaihong** [comment]
如果是charset=UTF-8没有设置，到好办。你可以在你的环境下验证下，修改方法如下。如果ok。就按这个思路修改，到时候merge到master分支。

你可以在。https://github.com/guonaihong/gout/blob/master/dataflow/req.go 文件代码下面

找到
req.Header.Add("Content-Type", "application/x-www-form-urlencoded")

修改为
为req.Header.Add("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8")

具体逻辑在addContextType函数里面。
* addContextType函数
```go
func (r *Req) addContextType(req *http.Request) {
	if r.wwwForm != nil {
		req.Header.Add("Content-Type", "application/x-www-form-urlencoded") //修改这里

	}

	if r.bodyEncoder != nil {
		switch bodyType := r.bodyEncoder.(encode.Encoder); bodyType.Name() {
		case "json":
			req.Header.Add("Content-Type", "application/json")
		case "xml":
			req.Header.Add("Content-Type", "application/xml")
		case "yaml":
			req.Header.Add("Content-Type", "application/x-yaml")
		}
	}

}
```

**Comment by botsphp** [comment]
这个方法我试过了，是可以的。但不同的程序里，可能编码不一样，所以这里的编码应该由用户自己去设置。

我自己还试过，通过 SetHeader 去设置ContetType，但 设置了 SetForm 以后，会覆盖之前 SetHeader的值，我觉得最合理的方案，应该是先检查Header 里有没有相同 Key。如果 Contet-Type 不存在，则再去覆盖，这样就是最完美的方案了。

**Comment by guonaihong** [comment]
可以，挺好的建议，加个SetCharSet接口，在ContextType 添加需要的字符编码。
比如
```go
gout.POST(url).SetWWWForm().SetCharSet("UTF-8").Do()
```
就会生成 这种application/x-www-form-urlencoded; charset=UTF-8  格式的http header

**Comment by botsphp** [comment]
另外，我建议暴露一个回调方法出来，允许去修 req 中的 Header 等信息，这样能足够灵活。
现在 SetForm 会覆盖 SetHeader 的信息，不方便。

**Comment by guonaihong** [comment]
现在就有，修改Request的方法。你可以看下如何编写gout插件，下面是文档。
https://github.com/antlabs/gout-middleware

**Comment by guonaihong** [comment]
周六，周日，简单看了下rfc 2616和衍生rfc。然后结合你那边的需求。修改方案如下。
加入NoAutoContentType() ，在处理x-www-form-urlencoded数据时，可以关闭gout自动加的Context-Type头文件。
然后使用自定义的Context-Type。大体和你的建议的思路差不多。
伪代码如下。
```go
func main() {
    err := gout.POST("127.0.0.1:1234").
        NoAutoContextType().
        SetHeader(gout.A{"content-type", "x-www-form-urlencoded; charset=UTF-8"}).
        SetWWWForm(
        gout.A{
            "elapsed_time", 0,
            "user_choice_index", -1, 
            "ts", 1608191572029,
        },
    ).Do()
    fmt.Println(err)
}
```

为什么废弃一开始加SetCharSet接口想法。
在简单浏览rfc7231之后，发现Content-Type里面的参数可能有很多，在不能穷尽 参数的前提。仓促的新加接口不是一个好的选择。
https://tools.ietf.org/html/rfc7231#section-3.1.1.5

**Comment by guonaihong** [comment]
v0.1.4版本已经合并到master分支，可以体验这个功能点了。

**Comment by botsphp** [comment]
Cool
