### ISSUE TITLE
能发起长连接吗？

### ISSUE THREAD

**Issue by Duslia997** [guonaihong/gout#266]
每次请求都是一个新的连接，能不能实现长连接呢？

**Comment by guonaihong** [comment]
我看下你在代码，现在配置就是长链接。

**Comment by Duslia997** [comment]
嗯嗯嗯，我在做压测的的时候发现一会fd就被用完了
`
func postForm() {
	url, key, value := constructUrlWithParam("/v1/st/form")
	msg := common.Body.GetOne()
	code := 0
	s := &model.STResponse{}
	err := gout.POST(url).
		SetForm(
			gout.H{
				"msg": msg,
			},
		).Code(&code).BindJSON(&s).Do()

	if err != nil {
		logs.Errorf("postForm request error: %#v", err.Error())
		common.EmitCounter("postForm.error", 1, map[string]string{})
		return
	}
	isSuccess := common.CheckStatusCode(code, "postForm")
	if !isSuccess {
		return
	}
	common.Check(s.Path, "1", "postForm.path")
	common.Check(s.Param, common.CombineParam(key, value), "postForm.param")
	common.Check(s.ParseBody, "msg:"+common.ReverseByte([]byte(msg)), "postForm.body")
}`

**Comment by guonaihong** [comment]
如果压测的话，可以配置专用的压测http.Client。你修改下gout.New()。修改我下面的就可以。
```go
package main

import (
	"fmt"

	"github.com/guonaihong/gout"
	"github.com/guonaihong/gout/dataflow"
)

func main() {
	msg := "hello"
	code := 0
	s := ""

	err := gout.New(&dataflow.DefaultBenchClient).POST("www.qq.com").
		SetForm(
			gout.H{
				"msg": msg,
			},
		).
		Code(&code).
		BindJSON(&s).
		Do()
	fmt.Println(err)
}

```

**Comment by Duslia997** [comment]
谢谢！ 解决啦

**Comment by guonaihong** [comment]
ok.
