### ISSUE TITLE
支持websocket吗？如果不的话，未来有计划吗？

### ISSUE THREAD

**Issue by awei0217** [guonaihong/gout#268]

**Comment by guonaihong** [comment]
http 和websocket是两个不同的模式，一个是req/rsp，一个是stream 。从结构上来说不好统一(这块你看下grpc stream模式就知道了)，你是有什么需求吗？

**Comment by guonaihong** [comment]
最近实现了一个websocket协议. https://github.com/guonaihong/tinyws
这两个协议, 区别还是挺大的. 就像我上面说的, 一个是流式(websocket). 一个是请求/响应式.(http)

这个issue关闭了, 这两个协议共性比较少, 没必要统一.
