### ISSUE TITLE
使用 retry 的时候能否知道是因为什么原因请求失败

### ISSUE THREAD

**Issue by DeemoASCII** [guonaihong/gout#272]
在开启 retry 模式之后,如果重试之后仍然失败,返回的 error 是 retry fail,不知道这个具体是因为什么原因出错了.

**Comment by guonaihong** [comment]
我刚刚看到https://github.com/pkg/errors 库，貌似实现了错误包装的功能也兼容go1.13的接口。这个我需要做点实验，如果可以。你的问题可以完美解决。

**Comment by guonaihong** [comment]
pr已提，明早我merge下。

**Comment by guonaihong** [comment]
ok。你用下v0.1.6版本就行。没有问题，大约明天会关闭这个issue

**Comment by DeemoASCII** [comment]
刚刚试用了一下,现在能够清楚地知道失败的原因了,非常感谢!

**Comment by DeemoASCII** [comment]
我有一个关于 retry 的小疑问,如果使用 retry 的方式重试,加入代理,代理是动态转发的那种,如果说请求是因为context deadline exceeded 超时的话,不管重试几次最后都会失败.但是如果我是在请求的外面使用 for 循环来循环请求,不加 retry,第一次失败了可能第二次就能成功,不会有重试几次都失败的情况,不知道这是为什么

**Comment by DeemoASCII** [comment]
代码: 
```go
err := gout.GET("https://httpbin.org/ip").
		Debug(true).
		SetTimeout(2 * time.Second).
		SetProxy("http://localhost:7890").
		Filter().Retry().Attempt(5).Do()
log.Infoln("%v", err)
for i := 0; i < 5; i++ {
  err := gout.GET("https://httpbin.org/ip").
  Debug(false).
  SetTimeout(2 * time.Second).
  SetProxy("http://localhost:7890").
  Do()
  log.Infoln("%v", err)
}
```
结果:
```bash
filter:retry #current attempt:0, wait time 115.823932ms
filter:retry #current attempt:1, wait time 344.319002ms
filter:retry #current attempt:2, wait time 481.464082ms
filter:retry #current attempt:3, wait time 868.705705ms
filter:retry #current attempt:4, wait time 2.769344198s
2021-03-18T15:25:33.835+0800    INFO    log/log.go:82   context deadline exceeded
2021-03-18T15:25:35.839+0800    INFO    log/log.go:82   Get "https://httpbin.org/ip": context deadline exceeded
2021-03-18T15:25:37.841+0800    INFO    log/log.go:82   Get "https://httpbin.org/ip": context deadline exceeded
2021-03-18T15:25:38.657+0800    INFO    log/log.go:82   <nil>
2021-03-18T15:25:38.903+0800    INFO    log/log.go:82   <nil>
2021-03-18T15:25:39.768+0800    INFO    log/log.go:82   <nil>

```

**Comment by guonaihong** [comment]
因为SetTimeout的超时时间是被传导到Retry的整个过程的，无论是重试2次还是3次，可以理解为整个Retry是用了同一个timeout计时器。举例来min(Retry加起来的retry time， SetTimeout的时间)。

所以解释第一个现象。retry time已经超过SetTimeout最大超时时间。所以直接返回错误。

**Comment by DeemoASCII** [comment]
那这样的话就是说 setimeout 和 retry 不能一起用了

**Comment by guonaihong** [comment]
可以一起用啊。set time out控制你总的超时时间。你可以设置一个总合理的超时时间。然后retry的每次重试时间可以设置小点。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月18日(周四) 下午4:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guonaihong/gout] 使用 retry 的时候能否知道是因为什么原因请求失败 (#272)




 
那这样的话就是说 setimeout 和 retry 不能一起用了

**Comment by DeemoASCII** [comment]
但是大多数情况下如果 set timeout设置1 分钟,可能第一次请求就把这 1 分钟用完了,设置得更长的话又不好控制整体的进度,我比较希望的是 set timeout 是每次 retry 单独的超时时间更好一点.不过也很感谢你的解答,现在还是先用 for 来控制一下吧.

**Comment by guonaihong** [comment]
可以。

**Comment by guonaihong** [comment]
这个话题讨论还挺好的。我发散了下，retry作为一个通用的模块，其实除了可以给gout使用，还可以给net/http模块使用。
解决单次retry timeout会更自然一点。
因为已经解决这个issue提出的问题，我会在新的issue里面实现，以及写下实现思路，到时候可以关注下。
