### ISSUE TITLE
能否提供一些全局的配置，如请求超时

### ISSUE THREAD

**Issue by fizzse** [guonaihong/gout#274]
每个请求里面都加一个SetTimeout,用起来会有些不是很爽

**Comment by guonaihong** [comment]
ok。

**Comment by guonaihong** [comment]
你用下0.1.7版本。功能已经ok

**Comment by fizzse** [comment]
go get: github.com/guonaihong/gout@v0.1.7: invalid version: unknown revision v0.1.7 
获取不到 v0.1.7

**Comment by guonaihong** [comment]
估计和tag有关系，我看下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月29日(周一) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guonaihong/gout] 能否提供一些全局的配置，如请求超时 (#274)




 
go get: ***@***.***: invalid version: unknown revision v0.1.7
 获取不到 v0.1.7

**Comment by guonaihong** [comment]
你先用
```bash

go get github.com/guonaihong/gout@v0.1.8
```
 下载，代理在处理v0.1.7有些问题。

**Comment by guonaihong** [comment]
我这边验证过是没有问题。如果你那边也没有问题，大约会在2天后关闭issue
