### ISSUE TITLE
把返回值写入文件时，是否可以添加自定义的内容，比如我想加一个\n作为结束

### ISSUE THREAD

**Issue by liuyeone** [guonaihong/gout#277]

**Comment by liuyeone** [comment]
现在我把多个返回值通过io.Writer写入文件时，多个返回值会合并在一行进行展示，这个能加个换行符之类的吗

**Comment by guonaihong** [comment]
兄弟我没有太明白，可否加个伪代码，告知下。你要哪个函数加这个功能。

**Comment by liuyeone** [comment]
err = gout.POST(requestUrl).SetTimeout(10 * time.Second).SetHeader(header).SetJSON(requestBody).BindBody(writer).Do()

**Comment by liuyeone** [comment]
比如返回值是: {"error_code":0},  上面的方法我调用多次，实际写到文件中的是
{"error_code":0}{"error_code":0}{"error_code":0}{"error_code":0}
我想要的结果是
{"error_code":0}
{"error_code":0}
{"error_code":0}
{"error_code":0}

**Comment by guonaihong** [comment]
可以声明一个新的类型writeLine，实现Write接口。然后在新的writeLine类型的Write除了实现现在有操作，再写一个'\n'就行。
如果不清楚，我中午午休，可以写个demo给你看下。

**Comment by liuyeone** [comment]
谢谢大佬，我还有一个问题想问下哈，如果我有多个协程同时调用BindBody(writer)在文件中写入内容，是不是可能会造成原本在一个返回body中的内容错乱，比如{"error{"error_code":0}_code":0}{"error_code":0}{"error_code":0}

**Comment by guonaihong** [comment]
你看下这个例子：
```go
package main

import (
	"fmt"
	"io"
	"os"
)

type writeAddLine struct {
	w io.Writer
}

func newWriteAddLine(w io.Writer) *writeAddLine {
	return &writeAddLine{w: w}
}

func (w *writeAddLine) Write(p []byte) (n int, err error) {
	n, err = w.w.Write(p)
	if err != nil {
		return n, err
	}

	_, err2 := w.w.Write([]byte{'\n'})
	if err != nil {
		return n, err2
	}

	return n + 1, nil
}

func main() {
	w := newWriteAddLine(os.Stdout)
	for i := 0; i < 10; i++ {
		w.Write([]byte(fmt.Sprintf("write :%d", i)))
	}

}
```

**Comment by guonaihong** [comment]
多个go程操作同一文件需要加锁。你也可以把数据流用chan汇总到一个go 程，专门写文件。

**Comment by liuyeone** [comment]
我现在有个需求是这样的，需要调用一个http接口1000次，接口返回的内容比较大，普遍在5M左右，我想用协程池并发访问，返回的结果不放内存直接写入到文件中，都写入完成后再解析文件中的内容，这种的可以吗？

**Comment by guonaihong** [comment]
这种可以吗？如何理解，你是担心内存，还是硬盘，还是网络的吞吐量？

**Comment by liuyeone** [comment]
担心内存，如果把数据流用chan汇总到一个go 程，是不是在内存中可能会存在很多数据

**Comment by guonaihong** [comment]
内存回收有gc。你可以先用不正常逻辑写，如果出现内存爆涨。可以使用sync.Pool优化下。

**Comment by liuyeone** [comment]
好的，谢谢，我去研究一下
