### ISSUE TITLE
gout支持发起CHUNK请求吗？

### ISSUE THREAD

**Issue by wivd** [guonaihong/gout#283]
gout支持发起CHUNK请求吗？不支持是否考虑支持一下。

**Comment by guonaihong** [comment]
good, 这个问题提得好, 我这两天看下.

**Comment by guonaihong** [comment]
ok, 我打算加个Chunked()接口, 然后client数据就使用Transfer-Encoding: chunked 编码的方式发送数据, 你看接口名可有别的想法?
没有的话, 这两天就可以实现功能.

**Comment by wivd** [comment]
点赞

**Comment by guonaihong** [comment]
你拉下v0.1.10版本, 已加Chunked()接口

**Comment by wivd** [comment]
好的，我测试看看

**Comment by guonaihong** [comment]
如果没有问题, 就close这个issue
