### ISSUE TITLE
希望支持忽略ssl验证

### ISSUE THREAD

**Issue by yimingsir** [guonaihong/gout#285]

**Comment by guonaihong** [comment]
可否详聊?
比如, 
你希望在访问哪个url是?
现在的行为是?
你希望的输出是什么?

**Comment by yimingsir** [comment]
使用自签证书的https请求，可以忽略证书的验证，curl 有这个选项

curl  -k, --insecure      Allow insecure server connections when using SSL

`
    tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    client := &http.Client{Transport: tr}
`

**Comment by guonaihong** [comment]
那你使用gout.New()里面传递下自定义的http.Client{}就可以了.

**Comment by yimingsir** [comment]
是的，我现在是这么用的。希望gout可以加入这个开关选项。

**Comment by guonaihong** [comment]
这个设计要慢慢捋下.  这里要修改到http.Client. 作为类型全局变量的它,  要谨慎点.

**Comment by guonaihong** [comment]
昨晚想了一个伪代码
```go
client := gout.NewClient(WithInsecureSkipVerify())
gout.New(client).SetBody("hello world").Do()
```
@yimingsir 你看可行?

**Comment by yimingsir** [comment]
可以的
@guonaihong

**Comment by guonaihong** [comment]
ok, 近期加下.

**Comment by wivd** [comment]
忽略ssl验证的功能，是否可以考虑做成全局配置的，类似于 设置超时时间的方式？类型的相关设置例如，3xx是否跳转，是否压缩请求，是否长链接等功能的配置进行一下统一？

**Comment by guonaihong** [comment]
@wivd 我理下.是可以统一风格.

**Comment by guonaihong** [comment]
@wivd 我想到一个设计
```go
// req可以多go程复, 只包含http.Client和选项信息
req := gout.NewOpt(WithInsecureSkipVerify(), WithClose3xxJump(), WithTimeout(3 * time.Second))

req.GET("www").SetBody("wwwo").Do()
```

**Comment by guonaihong** [comment]
@wivd @yimingsir 上面的API设计可还有建议, 没有的话, 就按这种风格开发, 到时候也会把中间件的一些代码移进主库里面.这样统一风格, 用起来更自然点.

**Comment by wivd** [comment]
1、风格统一一下比较好，这样用起来就比较方便了，一个地方就可以设置完了。超时时间、3xx是否调整、忽略证书、长链接、压缩请求、chunck请求或者代理设置，这些client的设置统一就行。
2、req.GET("www").SetBody("wwwo").Do() 这种方式的，是否考虑增加一个方法 了如request ,方法中可以设置请求方法，url，选项
例如  req.Request(请求模式,url地址，参数设置).xxxx 这样的请求方法

**Comment by guonaihong** [comment]
@wivd 第2点可否展开聊下. 比如多来点伪代码.

**Comment by wivd** [comment]
第二点伪代码。
H struct {
    AllowRedirect      bool  //302调整
    Timeout            int64  //超时
    Chunked            bool   //分块传输
    DisableKeepAlives  bool   //长链接
    DisableCompression bool   //是否压缩
    SkipVerifyTLS      bool  //证书校验
} 
post请求
resp,err:=gout.Request("post","http://www.xxx.com",H).SetBody("hello world").Do()
resp,err:=gout.Request("post","http://www.xxx.com",H).SetBody("hello world").Do().SetHeader().Do()
get请求
resp,err:=gout.Request("get","http://www.xxx.com",H).Do()
head请求
err:=gout.Request("head","http://www.xxx.com",H).Do()
返回结果，支持 clent的resp，这样方便用户自己处理结果。

**Comment by guonaihong** [comment]
@wivd 返回 resp的形式, 等go的泛型出来就会加上. 这个接口刚开始设计gout时考虑过, 因为go没有泛型, 所以就没有加.
比如有单鞋要[]byte类型的你要加个接口, 又有童鞋要string, 要加个接口, 设计中就会有很多冗余的地方.如果有泛型, 只有一个接口, 就可以适合多个类型. 即简洁又漂亮.
```go
resp, err := gout.Request().Do()
```
第二个点, 在执行过程中, 是否会提供设置option的方式, 
```go
H struct {
AllowRedirect bool //302调整
Timeout int64 //超时
Chunked bool //分块传输
DisableKeepAlives bool //长链接
DisableCompression bool //是否压缩
SkipVerifyTLS bool //证书校验
}
```
会提供上文的
```go
req := gout.NewWithOpt(WithInsecureSkipVerify(), WithClose3xxJump(), WithTimeout(3 * time.Second))
```
实现类型效果

由于go的很多参数是直接修改http.Client. 你可以理解是修改全局变量. go也是跑在多个线程上的语言, 所以gout的api尽量是线程安全的用法. 你现在给的api有点像js的方式, js是单线程语法, 这么参数没啥问题, 但是go里面操作go程是很常见的做法, 所以目前提供
```go
gout.NewWithOpt()
``` 的方式.

现在打算是, 很多固定的配置, 可以通过NewWithOpt 填充, 有一些个性化的配置, 可以通过SetXXX配置.

**Comment by wivd** [comment]
现在打算是, 很多固定的配置, 可以通过NewWithOpt 填充, 有一些个性化的配置, 可以通过SetXXX配置.

**Comment by wivd** [comment]
现在打算是, 很多固定的配置, 可以通过NewWithOpt 填充, 有一些个性化的配置, 可以通过SetXXX配置.

**Comment by wivd** [comment]
现在打算是, 很多固定的配置, 可以通过NewWithOpt 填充, 有一些个性化的配置, 可以通过SetXXX配置.

**Comment by wivd** [comment]
现在打算是, 很多固定的配置, 可以通过NewWithOpt 填充, 有一些个性化的配置, 可以通过SetXXX配置.----这个思路很好。
resp, err := gout.Request()
这个resp我指的是 golang标准库中的net/http中的Response结构体，毕竟有一些时候需要单独处理http响应。

**Comment by guonaihong** [comment]
@wivd 直接拿resp, 现在有个方法, 你看能否满足
```go
package main

import (
	"fmt"
	"io"
	"net/http"
	"os"

	"github.com/guonaihong/gout"
)

func main() {
	req, err := gout.GET("www.baidu.com").Request()
	if err != nil {
		panic(err.Error())
	}

	rsp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err.Error())
	}

	io.Copy(os.Stdout, rsp.Body)
	rsp.Body.Close()

	fmt.Printf("err:%v\n", err)
}

```

**Comment by wivd** [comment]
应该可以，我试试看

**Comment by guonaihong** [comment]
@yimingsir 忽略ssl的版本已经开发完, 使用v0.1.11版本即可体验.

**Comment by yimingsir** [comment]
> @yimingsir 忽略ssl的版本已经开发完, 使用v0.1.11版本即可体验.

👌🏻 谢谢
