### ISSUE TITLE
获取response对象

### ISSUE THREAD

**Issue by 12end** [guonaihong/gout#297]
看了下文档，并不支持获取响应或者bind response，导致对于响应的处理很不灵活，目前有个需求，拿到response的所有header，但是类似于BindHeader这种，必须要预定义一个struct，由于不确定response会有哪些header，所以很难实现。如果支持Bind response可以直接获取，或者希望加一个BindHeader(string)这样的直接把整段header返回的函数

**Comment by guonaihong** [comment]
返回http.Header类型可行?

**Comment by guonaihong** [comment]
ok, 最新版本已加上. 可以用下.

**Comment by 12end** [comment]
🐂，之前满足不了需求，用了github.com/asmcos/requests，这个库很易用，resp直接提供了一个R变量获取http.response。后面迭代的时候我再换回来gout。不过还有个小建议，添加一个BindResponse(&resp)，把响应对象绑定进去，能够最大化的提供自由度。之前看到了类似的Bind(&req,&resp)，但是和我期望的结果不太一样，也没有这个函数的文档

**Comment by guonaihong** [comment]
ok 这两天加下BindResponse。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月23日(周五) 上午9:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guonaihong/gout] 获取response对象 (#297)




 
🐂，之前满足不了需求，用了github.com/asmcos/requests，这个库很易用，resp直接提供了一个R变量获取http.response。后面迭代的时候我再换回来gout。不过还有个小建议，添加一个BindResponse(&amp;resp)，把响应对象绑定进去，能够最大化的提供自由度。之前看到了类似的Bind(&amp;req,&amp;resp)，但是和我期望的结果不太一样，也没有这个函数的文档

**Comment by guonaihong** [comment]
这个issue先关闭, 我重新提个实现BindResponse的issue
