### ISSUE TITLE
实现Response接口

### ISSUE THREAD

**Issue by guonaihong** [guonaihong/gout#299]
返回,http.Response类型

**Comment by 12end** [comment]
师傅实现了吗，遇到判断resp statuscode的问题，已有的bindxx方法还是没有办法很好解决

**Comment by guonaihong** [comment]
resp statuscode的问题是指？同一个接口返回不同的数据结构？

我今天晚上7点， 写下。

**Comment by 12end** [comment]
获取响应返回的状态码，目前已有的方法实现不了，自由度有点低，只要把BindResponse写了就解决了

**Comment by guonaihong** [comment]
代码已在master里面. 可以体验下, 没有问题, 就加个tag

**Comment by guonaihong** [comment]
v0.2.4 tag已加.欢迎使用.

**Comment by guonaihong** [comment]
先关闭issue
