### ISSUE TITLE
gout 是如何做multipart上传的？

### ISSUE THREAD

**Issue by wymli** [guonaihong/gout#303]
目前网上的做法是
```go
	var buff bytes.Buffer
	writer := multipart.NewWriter(&buff)
	// 添加form表单参数, 可以添加多个
	writer.WriteField("route_str", "xiaofei/1d7608ac3d4bdaa28c0bdc1805f03fc2.jpg")
	w, _ := writer.CreateFormFile("file_stream", "ywdhzxf.jpg")
	fd1, _ := os.Open("/Users/xiaofei/Downloads/ywdhzxf.jpg")
	defer fd1.Close()
	// 把文件流写入到缓冲区里去
	_, _ = io.Copy(w, fd1)
	writer.Close()
	//w.Write([]byte("this is a byte"))  如果有字节流直接写入就可以
	var client http.Client
	// 发送请求
	resp, err := client.Post("http://127.0.0.1/pic/upload", writer.FormDataContentType(), &buff)
```
我的疑惑在于
```go
w, _ := writer.CreateFormFile("file_stream", "ywdhzxf.jpg")
```
`createFormFile`的第二个参数似乎是冗余的，不太清楚这个field的作用，后续的文件字节流也是直接写入到w，和ywdhzxf.jpg无关

而python的接口，也没有用到filename这个field：
```python
resp = requests.post(url='http://127.0.0.1/pic/upload', files={'file_stream': res},
                     data={'route_str': 'xiaofei/1d7608ac3d4bdaa28c0bdc1805f03fc2.jpg'},
                     headers={'enctype': 'mutlipart/form-data'})
```

我观察到gout的对外接口，也没有filename这个field，请问是如何实现的呢？以及这个field的作用？
我简单阅读了下代码，似乎是让filename和field的key一样？

感谢！

**Comment by guonaihong** [comment]
你的问题,我 一个一个回答.
第1个.
> w, _ := writer.CreateFormFile("file_stream", "ywdhzxf.jpg")
createFormFile的第二个参数似乎是冗余的，不太清楚这个field的作用，后续的文件字节流也是直接写入到w，和ywdhzxf.jpg无关

首先, 这个参数不多于, 你可以抓包观察下. filename=“xx”的值, 就是CreateFormFile第二个参数控制的.
--2b0685e5b98e540f80b247d5e7c1283807aa07e62b827543859a6db765a8
Content-Disposition: form-data; name="voice"; filename="voice"
Content-Type: application/octet-stream

**Comment by guonaihong** [comment]
第2点
gout默认做法, 是取字段名, 作为filename的名字
可以看例子
https://github.com/guonaihong/gout#form-data

**Comment by wymli** [comment]
感谢，那么在服务端接受会有什么影响吗，既然filename可以任意设置

**Comment by guonaihong** [comment]
这个看你服务是否使用这个值, 通过标准库解析, 有个part.FileName()的属性, 可以取出这个值.

**Comment by guonaihong** [comment]
这个值, 和http.Header和query, 在某种意义上是一样, 通过某些外放的形式传了些数据 给服务端, 影响要看业务逻辑如何写的?

**Comment by wymli** [comment]
了解，感谢！

**Comment by guonaihong** [comment]
客气, 哈哈.
