### ISSUE TITLE
response的拦截器

### ISSUE THREAD

**Issue by yangheng-git** [guonaihong/gout#306]
我刚开始用gout。不知道是不是我用法不对。没找到类似java拦截器的东西。我尝试在callback中的修改response的body。然后发现用了callabck后，bingJson()就失效了。 能不能添加一个针对response的处理中间件，可以在修改response的值，和方便做统一的效验。然后bindJson()也不会失效。他的执行顺序应该在callabck和bindJson之前。

**Comment by guonaihong** [comment]
response的中件间没有还没有加。

**Comment by yangheng-git** [comment]
目前没有了。gout有群吗

**Comment by guonaihong** [comment]
> 目前没有了。gout有群吗

gout没有群， 建群会花费太多的社交时间。如果有问题和建议就在github 的issue讨论 也挺好的。

**Comment by guonaihong** [comment]
> 我刚开始用gout。不知道是不是我用法不对。没找到类似java拦截器的东西。我尝试在callback中的修改response的body。然后发现用了callabck后，bingJson()就失效了。 能不能添加一个针对response的处理中间件，可以在修改response的值，和方便做统一的效验。然后bindJson()也不会失效。他的执行顺序应该在callabck和bindJson之前。

golang的数据校验，一般采用struct tag的方式。伪代码如下
```go
type test struct {
   Value string `valid:"required"` 
}
```
如果Value为空，就会报错。
然后通过errors.Is() 函数做错误分解，就指导具体错误类型。

gout的设计也会参考这种方式。

**Comment by yangheng-git** [comment]
我的想法是处理通用逻辑。然后我仿照requestUse写了个小demo。你看下。 但是我刚写go,不太懂go的流处理，就写了伪代码。 
我fork了一份，你看看， https://github.com/yangheng-git/gout/commit/279e76ab8036ce2ec7cf2db8e01dd663f224f3c3
![image](https://user-images.githubusercontent.com/30469680/130761095-cca6901c-e8b8-4082-b403-edd45b0fa619.png)

**Comment by guonaihong** [comment]
@yangheng-git 这种方法是可以的. 
这样我提供两种姿势的数据校验, 一种基于tag的, 和主流思路一样. 
一种基于中间件, 可以做更丰富的事情.

**Comment by yangheng-git** [comment]
好的。期待新版本

**Comment by yangheng-git** [comment]
这个项目只有你维护吗，可以加入吗

**Comment by guonaihong** [comment]
可以，欢迎欢迎。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月29日(周日) 晚上8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guonaihong/gout] response的拦截器 (#306)




 
这个项目只有你维护吗，可以加入吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guonaihong** [comment]
这几天在一直在写websocket库，https://github.com/guonaihong/tinyws， 基本都写完了。还差些测试代码。
gout 这个需求我先留着， 等你参与。 go不清楚的直接问我好了。
