### ISSUE TITLE
SetProxy疑问

### ISSUE THREAD

**Issue by Sora233** [guonaihong/gout#313]
文档这句话是什么意思？
SetProxy 函数会修改Transport，请像对待全局变量一样对待SetProxy
我用gout.NewWithOpt() 创建的client，SetProxy会影响这个client后续所有的请求吗？

**Comment by guonaihong** [comment]
> 文档这句话是什么意思？
> SetProxy 函数会修改Transport，请像对待全局变量一样对待SetProxy

gout有两种形式的对象创建方式. 
#### 通过gout.Method函数发起http请求
如下这种形式
```go
gout.GET()
gout.POST()
```
这时候使用的是默认的http.Client. 对于这类用法就是变相的全局变量. 会影响到别的地址的gout代码.
所有不推荐使用SetProxy的.因为你不知道影响的范围是多大.

#### 通过```gout.NewWithOpt ``` or ```gout.New(&c)```
这类只影响生成的对象. 自己的对象自己管好, 影响不大.

> 我用gout.NewWithOpt() 创建的client，SetProxy会影响这个client后续所有的请求吗？

使用gout.NewWithOpt只影响你创建出来的对象.

**Comment by Sora233** [comment]
明白了，感谢回答
