### ISSUE TITLE
在请求时没有判断body是否为nil，直接使用了SetJSON，结果panic

### ISSUE THREAD

**Issue by listening3** [guonaihong/gout#317]
在请求时没有判断body是否为nil，直接使用了SetJSON，结果panic
看了一下SetJSON里面是判断的，但是没有生效
原因是NewBodyDecode返回参数是BodyDecode 指针，结构体nil指针返回出去后赋给bodyEncoder接口，bodyEncoder就不再是nil了
func (df *DataFlow) SetJSON(obj interface{}) *DataFlow {
	df.out.opt.ReqBodyType = "json"
	df.Req.bodyEncoder = encode.NewJSONEncode(obj)
	return df
}

**Comment by guonaihong** [comment]
感谢发现这个问题。你也可以提pr优化下。

**Comment by guonaihong** [comment]
@listening3 兄弟, 要不要试试看.

**Comment by listening3** [comment]
好啊李胜力-------- 原始邮件 --------发件人： guonaihong ***@***.***>日期： 2021年9月17日周五 11:04收件人： guonaihong/gout ***@***.***>抄送： listening3 ***@***.***>, Mention ***@***.***>主    题： Re: [guonaihong/gout] 在请求时没有判断body是否为nil，直接使用了SetJSON，结果panic (#317)

@listening3 兄弟, 要不要试试看.
