### ISSUE TITLE
bindheader出错

### ISSUE THREAD

**Issue by Alberthchang** [guonaihong/gout#325]
bingheader在存在多个setcookie的时候，获取不到所有的参数，建议改进一下

**Comment by guonaihong** [comment]
ok, 我看下. 可否贴下最小化你的问题的代码.

**Comment by Alberthchang** [comment]
问题解决了，事情是这样的，我使用`header := make(http.header)`，随后bindheaer，但是服务器给我的返回header中有两个Set-Cookie，所以我并不知道这样情况应该怎么做。。。

**Comment by Alberthchang** [comment]
另外，请问后期是否有考虑，将SetProxy代理做成一个开关，就是我虽然设置了，但是可控是否启用，方便调试

**Comment by guonaihong** [comment]
> 另外，请问后期是否有考虑，将SetProxy代理做成一个开关，就是我虽然设置了，但是可控是否启用，方便调试

现在版本就可以实现你的需求, 你可以看下这两行就知道怎么用了.
https://github.com/antlabs/pcurl/blob/master/pcurl.go#L242
https://github.com/antlabs/pcurl/blob/master/pcurl.go#L264

gout是链式+自状态改变的设计,  先``` g := gout.New() ``` 然后再根据条件设置API, 很容易就达到这个效果.

**Comment by Alberthchang** [comment]
师傅，又发现了一个问题，是不是代码默认将setheader的首字母大写了，这个能不能关闭？

**Comment by Alberthchang** [comment]
![image](https://user-images.githubusercontent.com/17517153/144310958-8573d6a1-dc41-48a9-ae46-dc41fb8d9d8a.png)

**Comment by Alberthchang** [comment]
师傅找到原因了，golang设置header的时候会自动大写

**Comment by Alberthchang** [comment]
建议将gout/encode/header.go中
```
func (h *HeaderEncode) Add(key string, v reflect.Value, sf reflect.StructField) error {
	h.r.Header.Add(key, valToStr(v, sf))
	return nil
}
```
修改为
```
func (h *HeaderEncode) Add(key string, v reflect.Value, sf reflect.StructField) error {
	h.r.Header[key] = []string{ valToStr(v, sf)}
	return nil
}
```

**Comment by guonaihong** [comment]
> 建议将gout/encode/header.go中
> 
> ```
> func (h *HeaderEncode) Add(key string, v reflect.Value, sf reflect.StructField) error {
> 	h.r.Header.Add(key, valToStr(v, sf))
> 	return nil
> }
> ```
> 
> 修改为
> 
> ```
> func (h *HeaderEncode) Add(key string, v reflect.Value, sf reflect.StructField) error {
> 	h.r.Header[key] = []string{ valToStr(v, sf)}
> 	return nil
> }
> ```

你是想绕开标准库的形为(标准库会对http header会首字母大写, 以及修改成-字符命名)? 


在原有接口上改目前不会, 可以新加个API之类的.

**Comment by Alberthchang** [comment]
对，就是标准库对http header的首字母大写的问题，期待师傅的api，我目前是直接把那个设置方式改了

**Comment by Alberthchang** [comment]
请问*dataflow.DataFlow 和*dataflow.Gout怎么转换啊？我现在有以下代码，但是涉及到多方面问题，请师傅帮忙看看
```
var reqGout interface{}
	tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
	client := &http.Client{Transport: tr}
	reqGout = gout.New(client)
	if debug {
		reqGout = reqGout.(*dataflow.DataFlow).Debug()
	}
	if httpProxy != "" {
		reqGout = reqGout.(*dataflow.DataFlow).SetProxy(httpProxy).SetGout
	}
	if socks5Proxy != "" {
		reqGout = reqGout.(*dataflow.Gout).SetSOCKS5(socks5Proxy).SetGout
	}

	return reqGout.(*dataflow.Gout)
```

**Comment by guonaihong** [comment]
```Debug```接口支持传false 和true, 你可以先优化这点.

**Comment by Alberthchang** [comment]
> true

func getClient() *dataflow.DataFlow {
	var reqGout interface{}
	tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
	client := &http.Client{Transport: tr}
	reqGout = gout.New(client)
	if httpProxy != "" && socks5Proxy != "" {
		reqGout = reqGout.(*dataflow.Gout).SetProxy(httpProxy).SetSOCKS5(socks5Proxy)
	} else if httpProxy != "" && socks5Proxy == "" {
		reqGout = reqGout.(*dataflow.Gout).SetProxy(httpProxy)
	} else if httpProxy == "" && socks5Proxy != "" {
		reqGout = reqGout.(*dataflow.Gout).SetSOCKS5(socks5Proxy)
	} else if httpProxy == "" && socks5Proxy == "" {
		reqGout = reqGout.(*dataflow.DataFlow)
	}
	return reqGout.(*dataflow.DataFlow)
}

**Comment by guonaihong** [comment]
> > true
> 
> ```
> func getClient() *dataflow.DataFlow {
> 	var reqGout interface{}
> 	tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
> 	client := &http.Client{Transport: tr}
> 	reqGout = gout.New(client)
> 	if httpProxy != "" && socks5Proxy != "" {
> 		reqGout = reqGout.(*dataflow.Gout).SetProxy(httpProxy).SetSOCKS5(socks5Proxy)
> 	} else if httpProxy != "" && socks5Proxy == "" {
> 		reqGout = reqGout.(*dataflow.Gout).SetProxy(httpProxy)
> 	} else if httpProxy == "" && socks5Proxy != "" {
> 		reqGout = reqGout.(*dataflow.Gout).SetSOCKS5(socks5Proxy)
> 	} else if httpProxy == "" && socks5Proxy == "" {
> 		reqGout = reqGout.(*dataflow.Gout).Debug()
> 	}
> 	return reqGout.(*dataflow.DataFlow)
> }
> ```

我写了个代码, 你试下
```go
package main

import (
        "crypto/tls"
        "net/http"

        "github.com/guonaihong/gout"
        "github.com/guonaihong/gout/dataflow"
)

func getClient(debugFlag bool, httpProxy, socks5Proxy string) *dataflow.DataFlow {
        tr := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
        client := &http.Client{Transport: tr}
        reqGout := gout.New(client)
        if httpProxy != "" {
                reqGout.SetProxy(httpProxy)
        }           
        if socks5Proxy != "" {
                reqGout.SetSOCKS5(socks5Proxy)
        }

        return reqGout.Debug(debugFlag)
}

func main() {
        reqGout := getClient(true, "", "")
        reqGout.SetMethod("GET").SetURL(":8080/").Do()
}
```

**Comment by Alberthchang** [comment]
emmm，这个代理是全局的么？换句话说是不是我初始化一次就都是这样了？

**Comment by guonaihong** [comment]
代理的配置是跟http.Client对象里的http.Transport走的. 
如果使用gout.New()传递自定义http.Client. 代理的配置就保存在你的的自定义的http.Client.Transport里面.
所以全不全局, 只看你这边如何使用.

**Comment by Alberthchang** [comment]
ok
