### ISSUE TITLE
关于gout的host

### ISSUE THREAD

**Issue by Alberthchang** [guonaihong/gout#328]
请问师父，我能否控制header里面的host？

**Comment by Alberthchang** [comment]
比如我能否强制修改host和发包ip不一致？

**Comment by guonaihong** [comment]
这两天忙着做核酸没看到. 我等会看下这个问题.

**Comment by guonaihong** [comment]
应该不行, gout底层用的标准的net/http相关的包. 标准库在处理host的值, 是直接用url里面取出来的. 
你看下NewRequestWithContext这个函数的实现. 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/5006959/158067790-0c9f5772-aa59-4ded-891b-3579b206c92a.png">

我明天抽个时间看下http.Request序列化的地方. 我有9成把握这个值修改不了(除了魔改标准库源代码)

**Comment by wxqchimei** [comment]
我试过了，可以在http.request = Host中设置，使用gout的话，可以采用
 get = gout.get("url")
req,_=get.Request()
req.Host="your host"
get.setRequest(req).Do()

**Comment by guonaihong** [comment]
> 我试过了，可以在http.Request.Host = Host中设置，使用gout的话，可以采用 get = gout.get("url") req,_=get.Request() req.Host="your host" get.setRequest(req).Do()

可以, 优秀, 是我这边思维定势了. 哈哈.

**Comment by guonaihong** [comment]
@Alberthchang 直接使用 @wxqchimei 这边给出的方法就行.

**Comment by Alberthchang** [comment]
> 我试过了，可以在http.Request.Host = Host中设置，使用gout的话，可以采用 get = gout.get("url") req,_=get.Request() req.Host="your host" get.setRequest(req).Do()

感谢
