### ISSUE TITLE
debug 无法解析json数组

### ISSUE THREAD

**Issue by carllhw** [guonaihong/gout#329]
https://github.com/guonaihong/gout/blob/24b222262efd50948521d7ff4c552b1140072607/color/color_core.go#L72

源码里仅能解析{}，无法解析[{}]

**Comment by guonaihong** [comment]
优秀: 不急我周日修下. 或者你提个pr也行.

**Comment by guonaihong** [comment]
修改下时间, 明天要早起做核酸. 今天晚上不写了, 明天吧.
