### ISSUE TITLE
请求url时，内崩

### ISSUE THREAD

**Issue by Matrix-X** [guonaihong/gout#334]
hi，请求解答一个问题，当前版本使用 github.com/guonaihong/gout v0.2.12

在使用gout的时候，发送请求会在这这里内崩，r.headerDecode ==false，请问这是什么情况回发生？

![198291652772268_ pic_hd](https://user-images.githubusercontent.com/317570/168753527-a4d0a2a5-a18c-429a-b5a1-422af24048ca.jpg)

**Comment by guonaihong** [comment]
可否把SetHeader的参数发下.

**Comment by Matrix-X** [comment]
找到问题了，是我这里的问题，传参数传错了，应该传nil，结果错写了false

不过这个有点小陷阱，玩意写错这个参数，就不知道怎么调试了

还好你提醒了一句 SetHeader , 感谢！
