### ISSUE TITLE
debug模式支持全局开关以及日志输出

### ISSUE THREAD

**Issue by HyetPang** [guonaihong/gout#338]
1. debug模式能否增加一个全局开关，这样可以在项目中可以做成配置，用配置文件来指定debug模式，而不是每次都要调用debug()方法
2. 增加debug模式日志输出到指定文件

**Comment by HyetPang** [comment]
我意思不是每次都需要去调用Debug()方法,而是像下面这样，设置一个全局的开关
```go
package main

import "github.com/guonaihong/gout"

func main() {
    gout.GlobalDebug := true // 这里设置了全局的debug开启，接下来的调用就不需要再调用debug()方法传参
	gout.GET("www.baidu.com").Do()
}
````

**Comment by guonaihong** [comment]
> 我意思不是每次都需要去调用Debug()方法,而是像下面这样，设置一个全局的开关
> 
> ```go
> package main
> 
> import "github.com/guonaihong/gout"
> 
> func main() {
>     gout.GlobalDebug := true // 这里设置了全局的debug开启，接下来的调用就不需要再调用debug()方法传参
> 	gout.GET("www.baidu.com").Do()
> }
> ```

可以啊， 不过为了和全局选项SetTimeout风格统一。
```go
gout.SetTimeout(time.Second * 1)
```
可以这么设计
```go
gout.SetDebug(/*true or false*/)
```

**Comment by HyetPang** [comment]
> > 我意思不是每次都需要去调用Debug()方法,而是像下面这样，设置一个全局的开关
> > ```go
> > package main
> > 
> > import "github.com/guonaihong/gout"
> > 
> > func main() {
> >     gout.GlobalDebug := true // 这里设置了全局的debug开启，接下来的调用就不需要再调用debug()方法传参
> > 	gout.GET("www.baidu.com").Do()
> > }
> > ```
> 
> 可以啊， 不过为了和全局选项SetTimeout风格统一。
> 
> ```go
> gout.SetTimeout(time.Second * 1)
> ```
> 
> 可以这么设计
> 
> ```go
> gout.SetDebug(/*true or false*/)
> ```

\(^o^)/~

**Comment by guonaihong** [comment]
https://github.com/guonaihong/gout/releases/tag/v0.3.1
使用v0.3.1版本，上面提的两个点都实现了。
