### ISSUE TITLE
识别response中的content-encoding

### ISSUE THREAD

**Issue by Sora233** [guonaihong/gout#343]
content-encoding会指定response body的压缩方法，希望可以支持自动识别常用的压缩，gzip, deflate, br等，相信这是一个比较common的部分

**Comment by guonaihong** [comment]
是指这里描述的内容？ https://developer.mozilla.org/zh-CN/docs/web/http/headers/content-encoding

**Comment by guonaihong** [comment]
备忘:这个issue完成了。在测试的时候发现，net/http里面已经做了gzip自动解码的动作，源代码位于 https://github.com/golang/go/blob/master/src/net/http/transport.go#L2211
位置http包-->transport.go -->readLoop函数内部。
AutoDecodeBody开关会实现deflate, br两种格式的解码。

**Comment by guonaihong** [comment]
有机会玩下v0.3.2版本，这个issue暂时关闭了。
