### ISSUE TITLE
有没有办法替换掉语言自带的json库？

### ISSUE THREAD

**Issue by panxl6** [guonaihong/gout#352]
Go语言自带的json库，性能相对json-iterator序列化库要差一些。有没有办法替换掉？

**Comment by guonaihong** [comment]
目前没开放这个功能。感兴趣可提个pr。就像gin里面的做法一样 提出公共函数，再使用编译tag选择。
https://github.com/gin-gonic/gin/tree/master/internal/json

**Comment by guonaihong** [comment]
或者我明后天抽个时间加上这个功能。

**Comment by panxl6** [comment]
那就辛苦大佬处理一下了

**Comment by panxl6** [comment]
提交了pr，帮忙确认一下
https://github.com/guonaihong/gout/pull/354

**Comment by guonaihong** [comment]
v0.3.6版本已加上。
