### ISSUE TITLE
SetWWWForm会带两个换行符导致请求失败

### ISSUE THREAD

**Issue by 21888** [guonaihong/gout#357]
![image](https://user-images.githubusercontent.com/80592877/218164559-8f1e81ee-d25f-46e1-8025-e71ecb7bf630.png)

请问这个地方两个换行符如何取消掉 发送的时候带着这两个换行符对方服务器就不给操作

**Comment by 21888** [comment]
不好意思这个问题已经解决了,302的事,他自动跳转了,我没看清楚文档,一直以为请求有问题

**Comment by guonaihong** [comment]
ok
