### ISSUE TITLE
SetHeader接口会自动把key字段变成第一个字母大写,其他字母小写.

### ISSUE THREAD

**Issue by noclear** [guonaihong/gout#361]
比如设置 SetHeader(gout.H{"TEST_SSS":"123"}).   header 自动转化为 Test_Sss: 123. 查看源码发现使用net/http库 Header.Add接口自动转化大小写. 请考虑header大小写自定义情况

**Comment by guonaihong** [comment]
你的需求是？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月3日(周五) 下午2:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [guonaihong/gout] SetHeader接口会自动把key字段变成第一个字母大写,其他字母小写. (Issue #361)




 
比如设置 SetHeader(gout.H{"TEST_SSS":"123"}).   header 自动转化为 Test_Sss: 123. 查看源码发现使用net/http库 Header.Add接口自动转化大小写. 请考虑header大小写自定义情况

**Comment by noclear** [comment]
Header 原样传入, 不用转成首字母大写其他字母小写

**Comment by guonaihong** [comment]
ok。后面新加一个SetHeaderRaw()接口，原样输出。

**Comment by guonaihong** [comment]
@noclear 用下v0.3.7版本试下。

**Comment by noclear** [comment]
> @noclear 用下v0.3.7版本试下。

OK了.谢谢
