### ISSUE TITLE
用自定义的http.Client 连接池不起作用

### ISSUE THREAD

**Issue by szsailing** [guonaihong/gout#364]
没用自定义的http.Client的代码如下，测试后连接池是可以正常起作用的
  err := gout.POST("http://192.168.0.7/tt1.php").
		//打开debug模式
		Debug(true).
		SetHeader(header).
		//设置json到请求body
		SetJSON(
			reqjson,
		).
		Do()

	if err != nil {
		fmt.Printf("err = %v\n", err)
	}
	
但是当我用自定义的http.Client的时候，就算把参数设置和Default的Client一样，连接池也不起作用

  tr := &http.Transport{
		IdleConnTimeout:       90 * time.Second,
	}
	c := &http.Client{
		Transport: tr,
	}
	err := gout.New(c).POST("http://192.168.0.7/tt1.php").
		//打开debug模式
		Debug(true).
		SetHeader(header).
		//设置json到请求body
		SetJSON(
			reqjson,
		).
		Do()

	if err != nil {
		fmt.Printf("err = %v\n", err)
	}
	
同样的代码，在不用gout而是纯http库来写的情况下，用自定义的http.Client，连接池是可以正常使用的。

请问这是我哪里没用对吗？

**Comment by guonaihong** [comment]
你每次都新建一个http.Client对象吗？
