### ISSUE TITLE
如何使用带账号密码的http代理和socks5

### ISSUE THREAD

**Issue by m7rick** [guonaihong/gout#386]
http的代理 setProxy("https://username:password@127.0.0.1:7890")
socks5 是 这样吗setSocks5("socks5://username:password@127.0.0.1:7890")

**Comment by guonaihong** [comment]
http proxy支持这么写，socks5的目前不行，我中午抽时间实现下。

**Comment by guonaihong** [comment]
给加上了，试下最新的commit c72fd8fc37610e15462dffa1fd00e00c59f22406

**Comment by m7rick** [comment]
感谢作者
