### ISSUE TITLE
能否支持Curl请求导入

### ISSUE THREAD

**Issue by Flipped199** [guonaihong/gout#391]
这个库用了很久了，挺好用的，翻了下文档，貌似只有curl导出，导入的话只有纯文本请求，希望支持curl导入就更好啦

**Comment by guonaihong** [comment]
有这个功能的。
https://github.com/antlabs/pcurl

**Comment by Flipped199** [comment]
> 有这个功能的，下面的是库和使用例子。 https://github.com/antlabs/pcurl
> 
> ```go
> package main
> 
> import (
>     "fmt"
>     "github.com/antlabs/pcurl"
>     "github.com/guonaihong/gout"
> )
> 
> func main() {
>     req, err := pcurl.ParseAndRequest(`curl -X POST -d 'hello world' www.qq.com`)
>     if err != nil {
>         fmt.Printf("err:%s\n", err)
>         return
>     }
> 
> 
>     resp := ""
>     err = gout.New().SetRequest(req).BindBody(&resp).Do()
> 
>     fmt.Println(err, "resp.size = ", len(resp))
> 
> }
> ```

哦哦好的 谢谢大佬
