### ISSUE TITLE
Do 函数上怎么做取消请求？

### ISSUE THREAD

**Issue by cchu1988** [guonaihong/gout#52]
按Golang的风格 要设计成 Do(ctx context.Context) error

https://github.com/guonaihong/gout/issues/32
这个callback的设计就有点不搭

**Comment by guonaihong** [comment]
Do(ctx context.Context) 的提议会在新版本实现。为了保证和现有代码兼容，形参会使用可变长参数。

**Comment by guonaihong** [comment]
callback的设计如果有想法的话，可以新启一个issue提。建议一个issus只讨论一件事。

**Comment by cchu1988** [comment]
> Do(ctx context.Context) 的提议会在新版本实现。为了保证和现有代码兼容，形参会使用可变长参数。

就像 js 一样？

PS: 突然起了兴趣 想看看在Golang里怎么实现一个Promise了  (虽然可能会和Golang的语言习惯完全不搭)

**Comment by guonaihong** [comment]
> > Do(ctx context.Context) 的提议会在新版本实现。为了保证和现有代码兼容，形参会使用可变长参数。

> 就像 js 一样？

js 不了解

> PS: 突然起了兴趣 想看看在Golang里怎么实现一个Promise了 (虽然可能会和Golang的语言习惯完全不搭)

可以看下这个项目 
https://github.com/fanliao/go-promise

**Comment by guonaihong** [comment]
@cchu1988 我想了下，还是新增函数来实现取消。

```go
gout.GET("127.0.0.1:8080/cancel").WithContext(ctx).Do()
```
这么设计的原因有
* go的标准库里面有同名函数，方便别人接入。

* Do函数是结束标记函数，加ctx就破化了一个函数做一件事情的设计初衷。
