### ISSUE TITLE
带namespace的debug 标记

### ISSUE THREAD

**Issue by guonaihong** [guonaihong/gout#57]
内容如下。

**Comment by solarhell** [comment]
这个debug我建议是加上一个namespace，比如我利用gout封装了一个微信小程序的sdk和一个支付宝小程序的sdk，我打开了debug，所有的请求都会输出到终端了，信息太杂乱。(我暂时用的是 `imroc/req`，发现的这个问题)

**Comment by guonaihong** [comment]
@solarhell 了解，我想到一个设计，扩展Debug函数， 第2个参数是io.Writer。

```go
Debug(true, os.Stdout)
var buf bytes.Buffer
Debug(true, &buf)
```

**Comment by solarhell** [comment]
我的意思是 这个debug 最好不是package级别的。 可以通过环境变量开启（不修改代码），或者针对单个请求、或者是 某个namespace下的请求。
我现在用`imroc/req`，只要开启了debug，所有用到这个包的请求都会输出调试信息。

**Comment by solarhell** [comment]
我举个例子，稍等

**Comment by solarhell** [comment]
![image](https://user-images.githubusercontent.com/10279583/66730445-6212be00-ee84-11e9-9a3d-a15d5fe73330.png)
这个包是这样开启debug的。

**Comment by solarhell** [comment]
如果项目里的依赖，也用了`imroc/req`，那么他们的请求也会被开启debug了。

**Comment by guonaihong** [comment]
gout的debug 是request级别的。请看下面的代码
```go
package main

import (
    "fmt"
    "github.com/guonaihong/gout"
)

func main() {
    err := gout.GET("127.0.0.1:1234").Debug(true).SetJSON(gout.H{"key": "val", "key2": "val2"}).Do()

    if err != nil {
        fmt.Printf("err = %v\n", err)
    }   

    err = gout.GET("127.0.0.1:1234").SetJSON(gout.H{"key1": "val1", "key2": "val2"}).Do()
    if err != nil {
        fmt.Printf("err = %v\n", err)
    }   
}
```
只有第一个请求会打印debug信息。

**Comment by solarhell** [comment]
嗯嗯 这个我看过了。 不过有的时候确实需要 全部开启debug，可能是一个业务流程中。

**Comment by solarhell** [comment]
所以还是希望能搞一个namespace级别的debug开关，我可以带着namespace初始化一个client。

**Comment by guonaihong** [comment]
ok。我想想。

**Comment by guonaihong** [comment]
我想到一个设计，伪代码如下
// Debug参数传入一个函数。函数里面可以自己设置环境变量。
// 这里设计为返回函数，是因为闭包比函数指针具备更好的API扩展性。
```go
func iosDebug(args ...interface{}) func() bool {
    return func() {
        len(os.Getenv("IOS_DEBUG")> 0
    }
}

func main() {
    gout.GET("127.0.0.1:1234").Debug(iosDebug()).Do()
}
```

**Comment by solarhell** [comment]
感觉可以哦

guonaihong <notifications@github.com>于2019年10月15日 周二下午9:17写道：

**Comment by guonaihong** [comment]
功能已开发完，欢迎试用。
