### ISSUE TITLE
希望提供重试的功能

### ISSUE THREAD

**Issue by hojit** [guonaihong/gout#94]
希望可以根据自定义条件进行重试，类似于resty这个golang http库的重试功能。

**Comment by guonaihong** [comment]
ok，v0.0.4或者v0.0.5会提供该功能

**Comment by hojit** [comment]
> ok，v0.0.4或者v0.0.5会提供该功能
会第一时间试用此功能

**Comment by guonaihong** [comment]
## 备注下算法来源:
https://amazonaws-china.com/cn/blogs/architecture/exponential-backoff-and-jitter/

了解完算法，就开撸。

**Comment by guonaihong** [comment]
算法看完了，只是y = ax + b的变种。外一个随机数防止一起发请求。
### 伪代码如下
```go
 err := GET("www.qq.com).
        Filter().
        Retry().
        Attempt(3). //最多尝试次数
        WaitTime(time.Millisecond * 10).          //基本等待时间
        MaxWaitTime(time.Millisecond * 800). //最长等待时间
        Do()
```
@hojit 看下伪代码有没有疑惑的地方。。。。

**Comment by guonaihong** [comment]
@hojit retry功能已经开发完毕。欢迎试用。

**Comment by hojit** [comment]
太棒了。

**Comment by guonaihong** [comment]
有什么想法，也可以直接提。
